import type { LexicalNode } from 'lexical'

import type { GeneratedDecoratorNodeBase } from '@/nodes/base/generate-decorator-node'

// Card nodes generated by generateDecoratorNode expose hasEditMode()/getIsVisibilityActive()
// which are not part of Lexical's base LexicalNode type. Cast $getNodeByKey results to this
// when these card-specific methods are needed.
// Additional methods are defined on specific subclasses but used generically across the codebase.
export type CardNode = LexicalNode &
  GeneratedDecoratorNodeBase & {
    isEmpty(): boolean
    __openInEditMode?: boolean
    clearOpenInEditMode?(): void
    selectPrevious?(): void
    selectNext?(): void
  }
